### ISSUE TITLE
运行train.py报错：AttributeError: 'EncDecSpeakerLabelModel' object has no attribute 'infer_segment'

### ISSUE THREAD

**Issue by wjddd** [Plachtaa/FAcodec#13]
您好，我在运行train.py的时候碰到以下报错：
```shell
Traceback (most recent call last):
  File "/home/tts/ref/ns3/train.py", line 496, in <module>
    main(args)
  File "/home/tts/ref/ns3/train.py", line 342, in main
    spk_logits = torch.cat([speaker_model.infer_segment(w16.cpu()[..., :wl])[1] for w16, wl in zip(waves_16k, wave_lengths)], dim=0)
  File "/home/tts/ref/ns3/train.py", line 342, in <listcomp>
    spk_logits = torch.cat([speaker_model.infer_segment(w16.cpu()[..., :wl])[1] for w16, wl in zip(waves_16k, wave_lengths)], dim=0)
  File "/opt/conda/envs/amphion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'EncDecSpeakerLabelModel' object has no attribute 'infer_segment'
```

nemo-toolkit的版本为1.21.0。
这个报错我在nemo的issues中找过，但是没有找到相关的问题。

**Comment by wjddd** [comment]
是nemo-toolkit版本问题，已解决。
